server:
  port: 1010

spring:
  datasource:
    url: jdbc:mysql://157.15.202.187:3306/tracker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: )u___peDah_A9qG
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

security:
  api-key: CHANGE_THIS_TO_A_LONG_RANDOM_STRING