services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tracker
      MYSQL_USER: root
      MYSQL_PASSWORD: )u___peDah_A9qG
      MYSQL_ROOT_PASSWORD: )u___peDah_A9qG
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: